Repository renpy/vscode-language-renpy, pull requests merged in 2022-07, with the labels that each got.

#155 added "Exclude Compiled Files From Workspace"
  package.json
  src/extension.ts
Labels: enhancement

#159 Updates publish workflow to support pre-releases
  .github/workflows/publish.yml
  Contributing.md
  package.json
Labels: ci/cd

#160 Adds basic PR validation
  .github/actions/setup/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pr-check.yml
  package-lock.json
  package.json
Labels: ci/cd

#162 Prepare v2.1.0 pre-release
  package.json
Labels: release

#166 Prepare v2.0.12 release
  CHANGELOG.md
  package.json
Labels: release

#173 Change `warnOnInvalidVariableNames` config to boolean
  .vscode/settings.json
  package.json
  src/diagnostics.ts
Labels: enhancement, topic:diagnostics
