Repository renpy/vscode-language-renpy, pull requests merged in 2022-05, with the labels that each got.

#101 New feature: styled strings
  examples/.vscode/settings.json
  src/extension.ts
  syntaxes/renpy.tmLanguage_2.json
Labels: enhancement, topic:syntax

#104 Small fixes in python block and new indenting rules
  language-configuration.json
  src/extension.ts
  syntaxes/renpy.tmLanguage_2.json
Labels: enhancement, topic:syntax

#110 chore: prepare 2.0.9 release
  CHANGELOG.md
  package.json
Labels: release

#109 Applied formatting to most files
  .vscode/launch.json
  snippets/snippets.json
  src/character.ts
  src/color.ts
  src/completion.ts
  src/definition.ts
  src/diagnostics.ts
  src/displayable.ts
  src/hover.ts
  src/navigation.ts
  src/navigationdata.ts
  src/outline.ts
  src/references.ts
  src/renpyauto.json
  src/semantics.ts
  src/signature.ts
  src/workspace.ts
  syntaxes/renpy.tmLanguage.json
  tsconfig.json
  tslint.json
Labels: enhancement

#118 Eslint fixes
  .eslintrc.json
  package.json
  src/character.ts
  src/color.ts
  src/completion.ts
  src/definition.ts
  src/diagnostics.ts
  src/displayable.ts
  src/extension.ts
  src/hover.ts
  src/navigation-data.ts
  src/navigation.ts
  src/outline.ts
  src/references.ts
  src/semantics.ts
  src/signature.ts
  src/workspace.ts
Labels: enhancement

#123 fix: Allow double underscore in variable names
  CHANGELOG.md
  src/diagnostics.ts
Labels: enhancement, topic:diagnostics

#125 chore: prepare 2.0.10 release
  CHANGELOG.md
  package.json
Labels: release

#112 New feature: Document tokenizer
  .eslintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  examples/.vscode/settings.json
  package.json
  src/debug-decorator.ts
  src/extension.ts
  src/navigation-data.ts
  src/token-definitions.ts
  src/token-patterns.ts
  src/tokenizer.ts
  src/types/esnext.regexp.d.ts
  src/types/renpy.tokens.d.ts
  src/types/token-patterns.d.ts
  src/utilities/stack.ts
  src/utilities/vector.ts
  syntaxes/renpy.tmLanguage_2.json
Labels: new feature, topic:syntax

#129 reg: version 2.0.10 changes
  CHANGELOG.md
  package.json
  src/diagnostics.ts
Labels: regression
