Repository renpy/vscode-language-renpy, pull requests merged in 2023-02, with the labels that each got.

#248 chore: prepare 2.0.15 release
  CHANGELOG.md
  package.json
Labels: release

#251 Prepare 2.1.3-pre-release
  package.json
Labels: pre-release

#254 Fix missing JSON files in extension package
  src/navigationdata.ts
  tsconfig.json
Labels: bug

#256 chore: prepare 2.0.16 release
  CHANGELOG.md
  package.json
Labels: release

#258 Adds GitHub Actions to Dependabot updates
  .github/dependabot.yml
Labels: ci/cd

#264 Draft: First check if a key already exists
  src/color.ts
Labels: bug

#265 Prepare 2.1.4-pre-release
  package.json
Labels: pre-release
