Repository renpy/vscode-language-renpy, pull requests merged in 2023-06, with the labels that each got.

#317 Tokenizer updates
  .prettierignore
  examples/tokenizer_tests.rpy
  examples/unit_test.rpy
  package.json
  src/color.ts
  src/tokenizer/atl-token-patterns.g.ts
  src/tokenizer/atl-token-patterns.ts
  src/tokenizer/common-token-patterns.ts
  src/tokenizer/debug-decorator.ts
  src/tokenizer/python-token-patterns.g.ts
  src/tokenizer/python-token-patterns.ts
  src/tokenizer/renpy-token-patterns.g.ts
  src/tokenizer/renpy-tokens.ts
  src/tokenizer/token-definitions.ts
  src/tokenizer/token-pattern-types.ts
  src/tokenizer/token-patterns.g.ts
  src/tokenizer/token-patterns.ts
  src/tokenizer/tokenizer.ts
  src/utilities/vector.ts
  syntax-to-token-pattern.py
  syntaxes/renpy.atl.tmLanguage.json
  syntaxes/renpy.python.tmLanguage.json
  syntaxes/renpy.tmLanguage.json
Labels: topic:syntax, t:semantic, pre-release

#319 Merge develop into master (Public Release)
  .gitignore
  .prettierignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  .vscodeignore
  README.md
  TODO.md
  browser.webpack.config.ts
  examples/.vscode/settings.json
  examples/game/script.rpy
  examples/hide_me!.rpyc
  examples/tokenizer_tests.rpy
  examples/unit_test.rpy
  language-configuration.json
  package-lock.json
  package.json
  snippets/snippets.json
  src/character.ts
  src/color.ts
  src/completion.ts
  src/decorator.ts
  src/definition.ts
  src/diagnostics.ts
  src/displayable.ts
  src/extension.ts
  src/hover.ts
  src/navigation-data.ts
  src/navigation.ts
  src/outline.ts
  src/references.ts
  src/renpyauto.json
  src/semantics.ts
  src/signature.ts
  src/tokenizer/atl-token-patterns.g.ts
  src/tokenizer/debug-decorator.ts
  src/tokenizer/python-token-patterns.g.ts
  src/tokenizer/renpy-token-patterns.g.ts
  src/tokenizer/renpy-tokens.ts
  src/tokenizer/token-definitions.ts
  src/tokenizer/token-pattern-types.ts
  src/tokenizer/token-patterns.g.ts
  src/tokenizer/tokenizer.ts
  src/types/esnext.regexp.d.ts
  src/utilities/hashset.ts
  src/utilities/stack.ts
  src/utilities/vector.ts
  syntax-to-token-pattern.py
  syntaxes/old.renpy.tmLanguage.json
  syntaxes/renpy.atl.tmLanguage.json
  syntaxes/renpy.python.tmLanguage.json
  syntaxes/renpy.tmLanguage.json
  tsconfig.json
  webpack.config.ts
Labels: release

#325 Release 2.2.0
  package-lock.json
  package.json
Labels: dependencies, release

#326 Update develop with master
  package-lock.json
  package.json
Labels: pre-release

#333 Bump version 2.3.1-pre-release
  package.json
Labels: pre-release

#347 Bump version 2.2.2
  package.json
Labels: release
